---
- name: Baseline Lab Setup
  hosts: all
  tasks:
    - name: Create Ansible user
      user:
        name: ansible
        system: yes
        comment: "Ansible Runner"
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_comment: ansible
        password: "{{ 'passw0rd' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    - name: Create symlink to /vagrant
      file:
        src: /vagrant
        dest: /home/ansible/class
        owner: ansible
        state: link
    - name: Grant ansible User sudo Access (needed for become)
      lineinfile:
        path: /etc/sudoers.d/ansible
        create: yes
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
        owner: root
        group: root
        mode: '0440'
    - name: Enable Password Authentication (for ssh-copy-id)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        state: present
      notify:
        - restart sshd
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
