---
# tasks file for db
- name: "Load package names for {{ ansible_distribution }}"
  include_vars: "{{ ansible_distribution }}.yaml"
- name: Install MySQL packages
  apt:
    name: '{{ packages.mysql }}'
    state: present
  become: yes
- name: Listen to public address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-addres"
    line: "bind-address = 0.0.0.0"
    state: present
  become: yes
  notify:
    - restart mysql
- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
- name: Create Application Database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: '{{ db_name }}'
    state: present
  become: yes
- name: Create Database User
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '*.*:ALL'
    state: present
    host: '%'
  no_log: yes
  become: yes
